#!/bin/bash

# Just a tiny little build script for the CI/CD Server <3

VERSION=$(grep current_version .bumpversion.cfg | head -n 1 | cut -d" " -f3)

echo "Bock v${VERSION}"

echo "🧹 Cleaning up"
rm -rf dist bock/ui/build

echo "👷‍♀️ Building UI"
export REACT_APP_CI=true
pushd bock/ui >>/dev/null || exit
yarn
yarn build
popd >>/dev/null || exit

# Remove Node Modules so that our Poetry builder doesn't go through a gazillion
# files!
TIMESTAMP=$(date "+%Y-%m-%dT%H.%M.%S")
NODE_MODULES_TEMP="/tmp/node_modules.$TIMESTAMP"
echo "👉 Moving node_modules to $NODE_MODULES_TEMP"
mv bock/ui/node_modules "$NODE_MODULES_TEMP"

echo "👷‍♀️ Building wheel and source tarball"
poetry install
poetry build -vvv

echo "👈 Restoring node_modules"
mv "$NODE_MODULES_TEMP" bock/ui/node_modules

echo "👷‍♀️ Building Docker image"
docker build -t "bock:$VERSION" .
docker build -t bock:latest .
