version: 2.1

jobs:
  build-ui:
    docker:
      - image: cimg/node
    steps:
      - checkout
      - run:
          command: .scripts/build-ui

  build-api:
    requires:
      - build-ui
    docker:
      - image: cimg/python
    steps:
      - checkout
      - run:
          command: .scripts/build-api

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-ui
      - build-api
