version: 2.1

jobs:
  build:
    docker:
      - image: afreeorange/build:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "bock-ui/package.json" }}
            - node-dependencies-

      - restore_cache:
          keys:
            - python-dependencies-{{ checksum "poetry.lock" }}
            - python-dependencies-

      - run:
          name: Install Dependencies
          command: |
            poetry install
            cd bock-ui && npm install

      - save_cache:
          paths:
            - bock-ui/node_modules
          key: node-dependencies-{{ checksum "bock-ui/package.json" }}

      - save_cache:
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
          key: python-dependencies-{{ checksum "poetry.lock" }}

      - run:
          name: Building package
          command: |
            git config user.email "auto@nikhil.io"
            git config user.name "CircleCI Builder"
            make build

      - persist_to_workspace:
          root: ./
          paths: ./*

  github-release:
    docker:
      - image: afreeorange/build:latest
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Releasing to GitHub
          command: /bin/bash ./.circleci/release

  # aws-deploy:
  #   docker:
  #     - image: afreeorange/build:latest
  #   steps:
  #     - add_ssh_keys
  #     - run:
  #         name: Deploying to AWS
  #         command: ssh -o StrictHostKeyChecking=no $AWS_USER@$AWS_HOST -p $AWS_PORT $AWS_DEPLOY_SCRIPT

workflows:
  version: 2.1

  build-and-release:
    jobs:
      - build
      - github-release:
          requires:
            - build
