version: 2.1

jobs:
  build-ui:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout
      - run:
          command: .scripts/build-ui

  build-api:
    docker:
      - image: cimg/python
    steps:
      - checkout
      - run:
          command: .scripts/build-api

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-ui
      - build-api:
          requires:
            - build-ui
