version: 2.1

orbs:
  gh: circleci/github-cli@1.0

jobs:
  build-ui:
    docker:
      - image: cimg/node:16.3.0
    environment:
      CI: true
    steps:
      - checkout
      - restore_cache:
          name: 🗃 Restoring package cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "bock/ui/yarn.lock" }}

      # This command is for yarn v1 only! See this:
      # https://circleci.com/docs/2.0/yarn/
      - run:
          name: Install Dependencies
          command: |
            cd bock/ui
            yarn install --frozen-lockfile --cache-folder /home/circleci/.cache/yarn
      - save_cache:
          name: 💾 Saving package cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "bock/ui/yarn.lock" }}
          paths:
            - ~/project/bock/ui/node_modules
      - run:
          name: Build UI
          command: |
            cd bock/ui
            yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-api:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          command: |
            .scripts/build-api
      - persist_to_workspace:
          root: .
          paths:
            - .

  release-to-github:
    docker:
      - image: "cimg/base:stable"
    steps:
      - attach_workspace:
          at: .
      - gh/setup
      - run:
          name: Release to Github
          command: |
            export VERSION=$(grep current_version .bumpversion.cfg | head -n 1 | cut -d" " -f3)
            if gh release list --repo afreeorange/bock | grep "$VERSION"; then
                echo "Found an existing release. Will overwrite. Go ahead and judge me."
                gh release delete "$VERSION" --repo afreeorange/bock --yes
            fi
            gh release create $VERSION ./dist/* --title "$VERSION" --repo afreeorange/bock
      - persist_to_workspace:
          root: .
          paths:
            - .

  release-to-dockerhub:
    docker:
      - image: docker:20
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +eo pipefail
            docker load -i /caches/app.tar || true
      - run:
          name: Build application Docker image
          command: |
            export VERSION=$(grep current_version .bumpversion.cfg | head -n 1 | cut -d" " -f3)
            docker build --tag afreeorange/bock:latest --tag afreeorange/"bock:$VERSION" . 
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar afreeorange/bock:latest
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - deploy:
          name: Push application Docker image
          command: |
            export VERSION=$(grep current_version .bumpversion.cfg | head -n 1 | cut -d" " -f3)
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USER" --password-stdin
            docker push afreeorange/bock:latest
            docker push afreeorange/"bock:$VERSION"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-ui
      - build-api:
          requires:
            - build-ui
      - release-to-github:
          requires:
            - build-api
      - release-to-dockerhub:
          requires:
            - build-api
