version: 2.1

jobs:
  build-ui:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout

      - restore_cache:
          name: 🗃 Restoring package cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "bock/ui/yarn.lock" }}

      # This command is for yarn v1 only! See this:
      # https://circleci.com/docs/2.0/yarn/
      - run:
          name: Install Dependencies
          command: |
            cd bock/ui
            yarn install --frozen-lockfile --cache-folder .cache/yarn

      - save_cache:
          name: 💾 Saving package cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "bock/ui/yarn.lock" }}
          paths:
            - ~/project/bock/ui/node_modules

      - run:
          command: |
            cd bock/ui
            yarn build

      - persist_to_workspace:
          root: .
          paths:
            - .

  # build-api:
  #   docker:
  #     - image: cimg/python:3.9.5
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         command: |
  #           ls -lA bock/ui/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-ui
      # - build-api:
      #     requires:
      #       - build-ui
