version: 2.1

orbs:
  gh: circleci/github-cli@1.0
  node: circleci/node@4.3

jobs:
  build-ui:
    docker:
      - image: cimg/node:16.3.0
    steps:
      - checkout

      - restore_cache:
          name: 🗃 Restoring package cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "bock/ui/yarn.lock" }}

      # This command is for yarn v1 only! See this:
      # https://circleci.com/docs/2.0/yarn/
      - run:
          name: Install Dependencies
          command: |
            cd bock/ui
            yarn install --frozen-lockfile --cache-folder /home/circleci/.cache/yarn

      - save_cache:
          name: 💾 Saving package cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "bock/ui/yarn.lock" }}
          paths:
            - ~/project/bock/ui/node_modules

      - run:
          name: Build UI
          command: |
            cd bock/ui
            yarn build

      - persist_to_workspace:
          root: .
          paths:
            - .

  build-api:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys: 
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths: 
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          command: |
            .scripts/build-api
            ls -lA dist/

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

  release-to-github:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - gh/release:
          context:
            - GITHUB_CREDS
          filters:
            branches:
              only:
                - main
          notes-file: CHANGELOG.md
          requires:
            - node/test
          tag: 1.0.0
          title: Test Release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-ui
      - build-api:
          requires:
            - build-ui
