#!/bin/bash

# Note: this clobbers any older releases with the same version.

if [[ ! -v "$GITHUB_TOKEN" ]]; then
    echo "GITHUB_TOKEN is not set. Aborting."
    exit 1
fi

VERSION=$(make version)
RELEASE_ARTIFACT="dist/bock-${VERSION}-py3-none-any.whl"

echo "Releasing to GitHub"
ghr \
    -t "$GITHUB_TOKEN" \
    -u "$CIRCLE_PROJECT_USERNAME" \
    -r "$CIRCLE_PROJECT_REPONAME" \
    -c "$CIRCLE_SHA1" \
    -delete "$VERSION" \
    "$RELEASE_ARTIFACT"

echo "Cleaning up"
make clean
