#!/bin/bash

source .scripts/common

echo "🧹 Cleaning up"
rm -rf dist

echo "👷‍♀️ Building wheel and source tarball"

if [[ ! -e bock/ui/cached_dist ]]; then
    echo "❌ Looks like you haven't built the UI. Quitting."
fi

echo "👉 Moving node_modules to $NODE_MODULES_TEMP"
mv bock/ui/node_modules "$NODE_MODULES_TEMP"

poetry install
poetry build -vvv

echo "👈 Restoring node_modules"
mv "$NODE_MODULES_TEMP" bock/ui/node_modules

echo "🚀 Finished API"
