#!/bin/bash

source .scripts/common

# Note: this clobbers any older releases with the same version.

if [[ -z "$GITHUB_TOKEN" ]]; then
    echo "GITHUB_TOKEN is not set. Aborting."
    exit 1
fi

echo "Releasing to GitHub"
if gh release list --repo afreeorange/bock | grep "$VERSION"; then
    echo "Found an existing release. Will overwrite. Go ahead and judge me."
    gh release delete "$VERSION" --repo afreeorange/bock --yes
fi
gh release create "$VERSION" ./dist/* --title "$VERSION" --repo afreeorange/bock

echo "Cleaning up"
make clean
